name: Keep Server Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Backend Server
        run: |
          echo "Pinging server at $(date)"
          response=$(curl -s -o /dev/null -w "%{http_code}" https://api.csxnaillounge.co.uk/ping)
          if [ $response -eq 200 ]; then
            echo "✅ Server is alive (HTTP $response)"
          else
            echo "❌ Server ping failed (HTTP $response)"
            exit 1
          fi
          
      - name: Ping Frontend
        run: |
          echo "Checking frontend at $(date)"
          response=$(curl -s -o /dev/null -w "%{http_code}" https://csxnaillounge.co.uk)
          if [ $response -eq 200 ]; then
            echo "✅ Frontend is alive (HTTP $response)"
          else
            echo "⚠️ Frontend check failed (HTTP $response)"
          fi
