name: Keep Server Alive

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch: # allow manual trigger

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend Server and Services with retries + timeout
        run: |
          echo "Pinging server at $(date)"
          success=false

          for i in {1..3}; do
            echo "Attempt $i..."

            # Timeout set to 15s per request
            ping_response=$(curl -s --max-time 15 -o /dev/null -w "%{http_code}" https://csx-nail-lounge-backend.onrender.com/ping || echo 000)
            services_response=$(curl -s --max-time 15 -o /dev/null -w "%{http_code}" https://csx-nail-lounge-backend.onrender.com/api/services || echo 000)

            echo "  /ping responded with HTTP $ping_response"
            echo "  /api/services responded with HTTP $services_response"

            if [ "$ping_response" -eq 200 ] && [ "$services_response" -eq 200 ]; then
              echo "✅ Both endpoints are alive"
              success=true
              break
            fi

            echo "⚠️  One or both endpoints failed, retrying in 10s..."
            sleep 10
          done

          if [ "$success" = true ]; then
            echo "🎉 Final Result: Server kept alive successfully."
          else
            echo "❌ Final Result: Server did not respond successfully after retries."
          fi
